version: '3'

services:

  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      - "8081:80" # map 8081 on the local host to port 80 on the docker image
    deploy:
      mode: replicated
      replicas: 1
    
  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.dockerfile
    restart: always
    ports:
      - "8082:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable connect_timeout=5"
      
  postgres:
    image: 'postgres:14.0'
    container_name: postgres
    ports:
      - "5432:5432" # close local psql database or the error will be: address already in use
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users
      - TZ=Asia/Kolkata
      - PGTZ=Asia/Kolkata
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/ # means go over to the folder 'project/db-data', this is where the docker container-
                                                      # stores the postgres data. So we have a local copy in computer and know where it is.
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro